# Generated by Django 5.1.1 on 2024-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_schoolclass_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='core.subject'),
        ),
    ]
