# Generated by Django 5.1.1 on 2025-02-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schoolclass_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
